"""Add serial_number to User

Revision ID: 0a4192c8bd35
Revises: 59186a157559
Create Date: 2025-06-25 15:08:12.770039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4192c8bd35'
down_revision = '59186a157559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_nfc_uid'), type_='unique')
        batch_op.create_unique_constraint('uq_user_serial_number', ['serial_number'])
        batch_op.drop_column('nfc_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nfc_uid', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_nfc_uid'), ['nfc_uid'])
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
