"""Add attendance_id to BreakSession

Revision ID: 7fc578dc886b
Revises: 0a4192c8bd35
Create Date: 2025-06-25 18:01:09.154907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc578dc886b'
down_revision = '0a4192c8bd35'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('break_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_breaksession_attendance',  # Name of the constraint
            'attendance',                  # Target table
            ['attendance_id'],             # Local column
            ['id']                         # Remote column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('break_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('attendance_id')

    # ### end Alembic commands ###
